# Generated by Django 2.1.2 on 2018-11-10 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='amount',
        ),
    ]
