# Generated by Django 2.1.2 on 2018-11-10 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_customers_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withhold',
            name='duration',
        ),
        migrations.AddField(
            model_name='withhold',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 14, 12, 52, 139235)),
        ),
        migrations.AddField(
            model_name='withhold',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 10, 14, 12, 52, 139235)),
        ),
    ]
