# Generated by Django 2.1.2 on 2018-11-10 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20181110_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withhold',
            name='from_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withhold',
            name='to_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
