# Generated by Django 2.1.2 on 2018-11-11 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20181111_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
