# Generated by Django 2.1.2 on 2018-11-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_auto_20181111_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
