# Generated by Django 2.1.2 on 2018-11-12 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_customers_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed')]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'enter 10 digits')]),
        ),
        migrations.AlterField(
            model_name='customers',
            name='pincode',
            field=models.CharField(default='', max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{6}$', 'enter 6 digits')]),
        ),
        migrations.AlterField(
            model_name='distributors',
            name='d_phone',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'enter 10 digits')]),
        ),
        migrations.AlterField(
            model_name='publications',
            name='language',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed')]),
        ),
        migrations.AlterField(
            model_name='publications',
            name='paper_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabets are allowed')]),
        ),
    ]
